[workspace]

resolver = "2"
members = [
  "nvparse_rs",
  "kernels/countchar",
  "kernels/getcharpos",
  "kernels/parsecsv",
  "kernelcodegen/kernelcodegen_macros",
  "kernelcodegen/kernelcodegen_types",
  "kernelcodegen/kernelcodegen"
]
