[package]
name = "nvparse_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
gpgpu = "0.2.0"
memmap = "0.7.0"
tqdm = "0.7.0"


[profile.release]
debug = true
